# Dependabot configuration
#
# For more information, please refer to:
#   https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:

# Maintain Go modules
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  ignore:
  # We prefer to keep control over Knative module imports.
  - dependency-name: knative.dev/*
  # The version of Kubernetes module imports needs to be consistent across all
  # modules. Besides, that version is determined by the current Knative version.
  - dependency-name: k8s.io/*

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
