# reviewdog configuration

runner:
  license-go:
    # Uses https://github.com/mattmoor/boilerplate-check
    cmd: >-
      boilerplate-check check
      --boilerplate=hack/boilerplate/boilerplate.go.txt
      --file-extension=go
      --exclude=vendor
    # See 'errorformat' documentation at https://vimhelp.org/quickfix.txt.html#error-file-format
    errorformat:
      - '%A%f:%l: %m'
      - '%C%.%#'
