name: CLI documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

   docs:
    name: CLI command reference
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Go caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: CLI ref check
      run: |
        TMCTL_GENERATE_DOCS=true go run main.go
        
        git_status="$(git status --porcelain)"
        if [[ ${git_status} ]]; then
            echo -e 'Generated CLI references are out-of-date. Please run `TMCTL_GENERATE_DOCS=true go run main.go`\n'
            echo "${git_status}"
            exit 1
        fi

